site_name: Documentation
dev_addr: '127.0.0.1:8080'
extra_css: 
    - assets/css/custom.css
theme:  
    custom_dir: overrides 
    favicon: assets/images/favicon-32x32.png
    features:
        - tabs
    language: en
    logo: assets/images/cp-logo.png
    name: material
    palette:
        primary: white
nav:
    - Home: index.md
    - Understand Cape:
        - Introduction: understand/index.md
        - Architecture: understand/architecture.md
        - Workflow: understand/workflow.md
    - Cape Core:
        - Introduction: cape-core/index.md
        - Coordinator: cape-core/coordinator.md
        - CLI installation: cape-core/cli-install.md
        - CLI usage: cape-core/cli-usage.md
    - Libraries: 
        - Introduction: libraries/index.md
        - Cape Python:
            - Overview: libraries/cape-python/index.md
            - Quickstart: libraries/cape-python/quickstart.md
            - Policies: libraries/cape-python/policies.md
            - Transformations: libraries/cape-python/transformations.md
            - API documentation: 
                - v1: '!include ./pythonv1/mkdocs.yml'
    - Best practices:
        - Introduction: best-practices/index.md
        - Running transformations: best-practices/running-transformations.md
    - Release notes:
        - Introduction: release-notes/index.md
        - July 2020: release-notes/30072020.md
        - June 2020: release-notes/26062020.md
plugins:    
    - search
    - monorepo
markdown_extensions:
    - admonition
    - codehilite
    - pymdownx.tabbed
    - pymdownx.superfences
    - toc:
        permalink: "#"


